@echo off
echo updating conda...
conda update -y conda
echo Installing Scikit-Image and it's dependences...
conda install -y scikit-image=0.13.0
echo Installation completed, press any key to close...
pause>null